  // File generated by FlutterFire CLI.
  // ignore_for_file: type=lint
  import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
  import 'package:flutter/foundation.dart'
      show defaultTargetPlatform, kIsWeb, TargetPlatform;

  /// Default [FirebaseOptions] for use with your Firebase apps.
  ///
  /// Example:
  /// ```dart
  /// import 'firebase_options.dart';
  /// // ...
  /// await Firebase.initializeApp(
  ///   options: DefaultFirebaseOptions.currentPlatform,
  /// );
  /// ```
  class DefaultFirebaseOptions {
    static FirebaseOptions get currentPlatform {
      if (kIsWeb) {
        return web;
      }
      switch (defaultTargetPlatform) {
        case TargetPlatform.android:
          return android;
        case TargetPlatform.iOS:
          return ios;
        case TargetPlatform.macOS:
          return macos;
        case TargetPlatform.windows:
          return windows;
        case TargetPlatform.linux:
          throw UnsupportedError(
            'DefaultFirebaseOptions have not been configured for linux - '
            'you can reconfigure this by running the FlutterFire CLI again.',
          );
        default:
          throw UnsupportedError(
            'DefaultFirebaseOptions are not supported for this platform.',
          );
      }
    }

    static const FirebaseOptions macos = FirebaseOptions(
      apiKey: 'AIzaSyBdZUc9wd4OPnaHc4YADz9e_z5D5ijSOZI',
      appId: '1:235919673805:ios:d29429324f6a6b253a9c84',
      messagingSenderId: '235919673805',
      projectId: 'popcornpicker-2b9f4',
      storageBucket: 'popcornpicker-2b9f4.appspot.com',
      iosBundleId: 'com.example.movieTmdbApp',
    );

    static const FirebaseOptions windows = FirebaseOptions(
      apiKey: 'AIzaSyCr8mp8zjiUFbXt6913niWLlUP6rWzNDf0',
      appId: '1:235919673805:web:1527ca9569a4c9333a9c84',
      messagingSenderId: '235919673805',
      projectId: 'popcornpicker-2b9f4',
      authDomain: 'popcornpicker-2b9f4.firebaseapp.com',
      storageBucket: 'popcornpicker-2b9f4.appspot.com',
      measurementId: 'G-6QW5CE6P40',
    );

    static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyCr8mp8zjiUFbXt6913niWLlUP6rWzNDf0',
      appId: '1:235919673805:web:1527ca9569a4c9333a9c84',
      messagingSenderId: '235919673805',
      projectId: 'popcornpicker-2b9f4',
      authDomain: 'popcornpicker-2b9f4.firebaseapp.com',
      storageBucket: 'popcornpicker-2b9f4.appspot.com',
      measurementId: 'G-6QW5CE6P40',
    );

    static const FirebaseOptions ios = FirebaseOptions(
      apiKey: 'AIzaSyBdZUc9wd4OPnaHc4YADz9e_z5D5ijSOZI',
      appId: '1:235919673805:ios:d29429324f6a6b253a9c84',
      messagingSenderId: '235919673805',
      projectId: 'popcornpicker-2b9f4',
      storageBucket: 'popcornpicker-2b9f4.appspot.com',
      iosBundleId: 'com.example.movieTmdbApp',
    );

    static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyBtQAAulq-7K8BIMmBRr_kxuhxh9uLqKkg',
      appId: '1:235919673805:android:220558ab975d07c23a9c84',
      messagingSenderId: '235919673805',
      projectId: 'popcornpicker-2b9f4',
      storageBucket: 'popcornpicker-2b9f4.appspot.com',
    );

  }